### ISSUE TITLE
Lens link dead

### ISSUE THREAD

**Issue by ersin-ertan** [http4k/http4k.github.io#2]
On https://www.http4k.org/guide/modules/core/
the Lens link to https://www21.in.tum.de/teaching/fp/SS15/papers/17.pdf

**Comment by arocnies** [comment]
All of the Lens links seem to work for me. Which link are you refering to specifically?

**Comment by ersin-ertan** [comment]
Fixed here https://github.com/http4k/http4k.github.io/commit/c113957b8ad140fc8198d4073ef24a2810103079#diff-34d49b98451d89f82b6321841694990d
